CREATE USER plsql IDENTIFIED BY motdepasse;

GRANT CREATE SESSION TO plsql;

GRANT
    CREATE TABLE,
    CREATE VIEW,
    CREATE SEQUENCE,
    CREATE PROCEDURE,
    CREATE TRIGGER,
    CREATE TYPE
TO plsql;

ALTER USER plsql
QUOTA UNLIMITED ON USERS;