-- =====================================================
-- Base de données RH
-- Script 01 - Création des tables
-- =====================================================

---------------------------------------------------------
-- REGION
---------------------------------------------------------

CREATE TABLE region
(
    region_id      NUMBER GENERATED BY DEFAULT AS IDENTITY,
    region_name    VARCHAR2(100) NOT NULL
);

---------------------------------------------------------
-- COUNTRY
---------------------------------------------------------

CREATE TABLE country
(
    country_id     CHAR(2),
    country_name   VARCHAR2(100) NOT NULL,
    region_id      NUMBER NOT NULL
);

---------------------------------------------------------
-- LOCATION
---------------------------------------------------------

CREATE TABLE location
(
    location_id    NUMBER GENERATED BY DEFAULT AS IDENTITY,

    street         VARCHAR2(200),

    postal_code    VARCHAR2(20),

    city           VARCHAR2(100) NOT NULL,

    state_name     VARCHAR2(100),

    country_id     CHAR(2) NOT NULL
);

---------------------------------------------------------
-- DEPARTMENT
---------------------------------------------------------

CREATE TABLE department
(
    department_id      NUMBER GENERATED BY DEFAULT AS IDENTITY,

    department_name    VARCHAR2(100) NOT NULL,

    location_id        NUMBER
);

---------------------------------------------------------
-- JOB
---------------------------------------------------------

CREATE TABLE job
(
    job_id          NUMBER GENERATED BY DEFAULT AS IDENTITY,

    job_title       VARCHAR2(100) NOT NULL,

    min_salary      NUMBER(10,2),

    max_salary      NUMBER(10,2)
);

---------------------------------------------------------
-- EMPLOYEE
---------------------------------------------------------

CREATE TABLE employee
(
    employee_id         NUMBER GENERATED BY DEFAULT AS IDENTITY,

    first_name          VARCHAR2(100),

    last_name           VARCHAR2(100) NOT NULL,

    email               VARCHAR2(200) NOT NULL,

    phone_number        VARCHAR2(30),

    hire_date           DATE NOT NULL,

    salary              NUMBER(10,2) NOT NULL,

    commission_pct      NUMBER(5,2),

    manager_id          NUMBER,

    department_id       NUMBER,

    job_id              NUMBER
);

---------------------------------------------------------
-- LEAVE_TYPE
---------------------------------------------------------

CREATE TABLE leave_type
(
    leave_type_id       NUMBER GENERATED BY DEFAULT AS IDENTITY,

    leave_name          VARCHAR2(100) NOT NULL
);

---------------------------------------------------------
-- LEAVE_REQUEST
---------------------------------------------------------

CREATE TABLE leave_request
(
    leave_id            NUMBER GENERATED BY DEFAULT AS IDENTITY,

    employee_id         NUMBER NOT NULL,

    leave_type_id       NUMBER NOT NULL,

    start_date          DATE NOT NULL,

    end_date            DATE NOT NULL,

    comment_text        VARCHAR2(1000)
);

---------------------------------------------------------
-- TRAINING
---------------------------------------------------------

CREATE TABLE training
(
    training_id         NUMBER GENERATED BY DEFAULT AS IDENTITY,

    training_name       VARCHAR2(200) NOT NULL,

    provider            VARCHAR2(200),

    duration_days       NUMBER
);

---------------------------------------------------------
-- EMPLOYEE_TRAINING
---------------------------------------------------------

CREATE TABLE employee_training
(
    employee_id         NUMBER,

    training_id         NUMBER,

    training_date       DATE,

    score               NUMBER(5,2)
);

---------------------------------------------------------
-- REVIEW
---------------------------------------------------------

CREATE TABLE review
(
    review_id           NUMBER GENERATED BY DEFAULT AS IDENTITY,

    employee_id         NUMBER NOT NULL,

    review_date         DATE NOT NULL,

    score               NUMBER(3,1),

    comments            VARCHAR2(4000)
);

---------------------------------------------------------
-- SALARY_HISTORY
---------------------------------------------------------

CREATE TABLE salary_history
(
    history_id          NUMBER GENERATED BY DEFAULT AS IDENTITY,

    employee_id         NUMBER NOT NULL,

    old_salary          NUMBER(10,2),

    new_salary          NUMBER(10,2),

    change_date         DATE NOT NULL,

    changed_by          VARCHAR2(100)
);