-- Script 09_04 - Insertion des entretiens annuels

INSERT INTO review (employee_id, review_date, score, comments) VALUES (135, DATE '2026-02-10', 4.6, 'Très bonne progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (71, DATE '2025-09-04', 2.7, 'Performance conforme aux attentes.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (77, DATE '2021-05-23', 4.1, 'Objectifs atteints.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (43, DATE '2022-10-07', 2.7, 'Compétences techniques en progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (57, DATE '2026-10-03', 3.4, 'Compétences techniques en progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (26, DATE '2023-09-15', 5.0, 'Compétences techniques en progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (160, DATE '2022-01-26', 3.7, 'Excellente implication dans les projets.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (52, DATE '2022-04-06', 4.2, 'Compétences techniques en progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (86, DATE '2023-09-10', 4.8, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (1, DATE '2021-02-11', 3.0, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (25, DATE '2026-08-08', 4.7, 'Compétences techniques en progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (194, DATE '2024-05-19', 3.1, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (163, DATE '2021-09-10', 3.3, 'Compétences techniques en progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (49, DATE '2025-01-21', 3.3, 'Compétences techniques en progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (145, DATE '2021-02-17', 2.2, 'Compétences techniques en progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (60, DATE '2022-02-21', 4.2, 'Compétences techniques en progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (157, DATE '2023-05-19', 4.4, 'Axes d''amélioration identifiés.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (87, DATE '2026-07-23', 3.9, 'Performance conforme aux attentes.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (141, DATE '2021-03-07', 4.3, 'Des efforts sont attendus sur la communication.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (144, DATE '2026-11-10', 3.1, 'Axes d''amélioration identifiés.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (181, DATE '2024-05-01', 4.3, 'Performance conforme aux attentes.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (109, DATE '2026-08-02', 4.6, 'Axes d''amélioration identifiés.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (101, DATE '2023-07-20', 4.3, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (78, DATE '2021-05-23', 4.4, 'Performance conforme aux attentes.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (135, DATE '2022-07-20', 3.1, 'Excellente implication dans les projets.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (143, DATE '2021-03-18', 3.8, 'Axes d''amélioration identifiés.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (57, DATE '2026-11-04', 3.6, 'Très bonne progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (24, DATE '2026-05-22', 4.6, 'Axes d''amélioration identifiés.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (158, DATE '2021-10-11', 3.6, 'Axes d''amélioration identifiés.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (144, DATE '2023-03-07', 3.1, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (72, DATE '2021-11-25', 4.7, 'Objectifs atteints.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (84, DATE '2022-05-12', 4.1, 'Excellente implication dans les projets.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (170, DATE '2025-06-09', 2.4, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (128, DATE '2022-12-27', 3.0, 'Objectifs atteints.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (44, DATE '2026-09-01', 4.2, 'Performance conforme aux attentes.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (148, DATE '2024-12-02', 2.2, 'Très bonne progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (164, DATE '2025-08-05', 2.8, 'Performance conforme aux attentes.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (150, DATE '2023-08-13', 2.2, 'Performance conforme aux attentes.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (6, DATE '2026-01-01', 4.0, 'Compétences techniques en progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (22, DATE '2021-12-05', 4.4, 'Performance conforme aux attentes.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (71, DATE '2022-03-07', 3.8, 'Des efforts sont attendus sur la communication.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (130, DATE '2022-02-01', 4.9, 'Des efforts sont attendus sur la communication.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (149, DATE '2021-03-02', 2.4, 'Compétences techniques en progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (115, DATE '2025-07-01', 4.5, 'Objectifs atteints.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (71, DATE '2026-11-25', 2.1, 'Excellente implication dans les projets.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (50, DATE '2024-04-18', 2.8, 'Très bonne progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (119, DATE '2022-11-05', 4.2, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (163, DATE '2025-02-15', 2.7, 'Des efforts sont attendus sur la communication.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (185, DATE '2024-12-10', 2.7, 'Performance conforme aux attentes.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (131, DATE '2021-05-08', 4.7, 'Des efforts sont attendus sur la communication.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (126, DATE '2026-06-24', 4.6, 'Performance conforme aux attentes.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (38, DATE '2023-12-26', 3.8, 'Des efforts sont attendus sur la communication.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (86, DATE '2025-06-22', 3.4, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (64, DATE '2021-03-10', 4.7, 'Très bonne progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (160, DATE '2022-11-15', 2.2, 'Des efforts sont attendus sur la communication.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (121, DATE '2024-11-28', 2.8, 'Compétences techniques en progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (97, DATE '2022-06-14', 2.2, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (93, DATE '2024-11-25', 2.6, 'Des efforts sont attendus sur la communication.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (14, DATE '2024-11-04', 2.1, 'Excellente implication dans les projets.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (105, DATE '2021-08-20', 4.4, 'Des efforts sont attendus sur la communication.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (145, DATE '2025-10-22', 2.3, 'Performance conforme aux attentes.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (196, DATE '2024-10-25', 3.4, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (83, DATE '2023-02-03', 3.0, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (182, DATE '2026-08-28', 3.3, 'Compétences techniques en progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (132, DATE '2024-12-05', 2.4, 'Objectifs atteints.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (85, DATE '2021-10-03', 2.0, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (1, DATE '2026-07-01', 3.0, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (171, DATE '2022-10-28', 4.3, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (174, DATE '2021-05-07', 3.5, 'Objectifs atteints.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (27, DATE '2022-05-12', 4.3, 'Performance conforme aux attentes.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (167, DATE '2022-02-27', 2.2, 'Performance conforme aux attentes.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (43, DATE '2023-03-20', 2.6, 'Compétences techniques en progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (31, DATE '2025-04-05', 4.2, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (37, DATE '2023-12-17', 3.0, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (18, DATE '2025-11-06', 4.2, 'Des efforts sont attendus sur la communication.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (113, DATE '2026-08-19', 3.4, 'Axes d''amélioration identifiés.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (31, DATE '2025-02-21', 2.3, 'Axes d''amélioration identifiés.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (133, DATE '2023-12-28', 3.7, 'Très bonne progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (170, DATE '2023-08-04', 4.7, 'Très bonne progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (120, DATE '2025-04-18', 2.9, 'Objectifs atteints.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (142, DATE '2025-10-14', 3.4, 'Très bonne progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (19, DATE '2024-11-05', 3.6, 'Axes d''amélioration identifiés.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (24, DATE '2023-09-12', 3.9, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (52, DATE '2021-06-18', 3.2, 'Très bonne progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (132, DATE '2026-02-26', 2.5, 'Compétences techniques en progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (183, DATE '2022-06-08', 3.1, 'Objectifs atteints.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (13, DATE '2025-06-01', 3.4, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (124, DATE '2026-01-21', 2.3, 'Très bonne progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (162, DATE '2022-05-06', 2.5, 'Compétences techniques en progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (43, DATE '2024-04-17', 3.2, 'Performance conforme aux attentes.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (189, DATE '2022-08-08', 3.5, 'Compétences techniques en progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (55, DATE '2021-07-10', 4.6, 'Axes d''amélioration identifiés.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (115, DATE '2022-01-21', 5.0, 'Objectifs atteints.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (176, DATE '2024-03-22', 4.5, 'Excellente implication dans les projets.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (189, DATE '2024-05-24', 4.4, 'Excellente implication dans les projets.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (34, DATE '2023-04-11', 2.1, 'Objectifs atteints.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (156, DATE '2024-08-09', 2.6, 'Des efforts sont attendus sur la communication.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (139, DATE '2024-05-12', 2.5, 'Axes d''amélioration identifiés.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (108, DATE '2025-02-21', 4.6, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (146, DATE '2023-06-15', 5.0, 'Des efforts sont attendus sur la communication.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (20, DATE '2021-12-09', 3.1, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (51, DATE '2025-02-09', 3.7, 'Objectifs atteints.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (186, DATE '2021-10-03', 2.6, 'Axes d''amélioration identifiés.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (30, DATE '2024-05-01', 2.0, 'Objectifs atteints.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (2, DATE '2023-04-06', 4.1, 'Compétences techniques en progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (145, DATE '2022-05-27', 4.5, 'Très bonne progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (65, DATE '2024-09-22', 4.2, 'Performance conforme aux attentes.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (62, DATE '2022-01-14', 3.4, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (198, DATE '2026-02-06', 3.6, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (195, DATE '2023-02-17', 2.5, 'Performance conforme aux attentes.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (68, DATE '2022-02-22', 2.9, 'Compétences techniques en progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (74, DATE '2026-01-20', 2.7, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (64, DATE '2022-09-27', 3.2, 'Performance conforme aux attentes.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (15, DATE '2021-03-06', 5.0, 'Performance conforme aux attentes.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (82, DATE '2023-04-13', 3.9, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (46, DATE '2024-10-17', 2.0, 'Excellente implication dans les projets.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (87, DATE '2023-02-20', 2.0, 'Des efforts sont attendus sur la communication.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (181, DATE '2021-04-20', 4.9, 'Très bonne progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (169, DATE '2021-10-19', 4.9, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (192, DATE '2026-07-12', 4.8, 'Des efforts sont attendus sur la communication.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (181, DATE '2026-09-01', 2.0, 'Compétences techniques en progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (125, DATE '2022-10-15', 5.0, 'Très bonne progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (31, DATE '2026-06-01', 3.6, 'Performance conforme aux attentes.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (12, DATE '2023-12-20', 4.5, 'Objectifs atteints.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (21, DATE '2025-08-18', 2.6, 'Excellente implication dans les projets.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (17, DATE '2021-05-07', 3.6, 'Performance conforme aux attentes.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (125, DATE '2024-04-14', 2.9, 'Compétences techniques en progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (107, DATE '2022-08-09', 4.2, 'Compétences techniques en progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (168, DATE '2021-12-16', 2.9, 'Performance conforme aux attentes.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (62, DATE '2023-04-26', 4.5, 'Excellente implication dans les projets.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (89, DATE '2022-11-19', 3.3, 'Compétences techniques en progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (86, DATE '2024-04-15', 3.9, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (62, DATE '2021-12-05', 3.3, 'Axes d''amélioration identifiés.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (114, DATE '2025-06-16', 5.0, 'Objectifs atteints.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (83, DATE '2025-05-06', 3.8, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (199, DATE '2023-10-14', 3.7, 'Objectifs atteints.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (102, DATE '2024-05-02', 2.7, 'Performance conforme aux attentes.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (43, DATE '2025-08-17', 2.3, 'Compétences techniques en progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (195, DATE '2024-09-10', 2.0, 'Performance conforme aux attentes.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (129, DATE '2025-05-04', 4.5, 'Objectifs atteints.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (170, DATE '2023-11-21', 2.8, 'Compétences techniques en progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (113, DATE '2026-08-04', 3.6, 'Axes d''amélioration identifiés.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (127, DATE '2026-04-14', 2.8, 'Performance conforme aux attentes.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (142, DATE '2023-02-22', 5.0, 'Des efforts sont attendus sur la communication.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (7, DATE '2021-06-28', 3.5, 'Compétences techniques en progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (90, DATE '2025-08-08', 3.3, 'Très bonne progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (142, DATE '2025-06-20', 2.5, 'Très bonne progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (59, DATE '2021-03-09', 3.7, 'Excellente implication dans les projets.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (115, DATE '2026-11-21', 3.5, 'Des efforts sont attendus sur la communication.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (76, DATE '2026-03-14', 3.4, 'Axes d''amélioration identifiés.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (36, DATE '2021-06-08', 3.1, 'Compétences techniques en progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (165, DATE '2022-12-01', 2.6, 'Performance conforme aux attentes.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (193, DATE '2024-02-09', 4.8, 'Très bonne progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (91, DATE '2026-12-01', 4.0, 'Objectifs atteints.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (162, DATE '2022-09-08', 2.6, 'Performance conforme aux attentes.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (70, DATE '2023-11-17', 3.0, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (108, DATE '2021-06-03', 2.1, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (192, DATE '2025-02-08', 4.3, 'Axes d''amélioration identifiés.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (170, DATE '2026-02-22', 3.2, 'Axes d''amélioration identifiés.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (70, DATE '2022-05-23', 3.7, 'Objectifs atteints.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (185, DATE '2026-01-17', 3.0, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (86, DATE '2026-06-20', 2.9, 'Très bonne progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (2, DATE '2024-04-13', 3.5, 'Compétences techniques en progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (31, DATE '2024-09-16', 2.8, 'Très bonne progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (22, DATE '2025-05-24', 5.0, 'Très bonne progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (50, DATE '2021-06-24', 2.3, 'Objectifs atteints.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (142, DATE '2022-09-23', 3.8, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (45, DATE '2021-10-28', 4.6, 'Performance conforme aux attentes.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (103, DATE '2024-04-25', 3.5, 'Très bonne progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (1, DATE '2023-08-05', 4.0, 'Très bonne progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (138, DATE '2021-01-25', 4.2, 'Des efforts sont attendus sur la communication.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (104, DATE '2022-03-28', 2.3, 'Des efforts sont attendus sur la communication.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (51, DATE '2023-06-27', 4.1, 'Objectifs atteints.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (53, DATE '2022-08-06', 2.1, 'Très bonne progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (144, DATE '2023-03-27', 3.4, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (29, DATE '2023-04-23', 4.1, 'Très bonne progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (42, DATE '2022-06-16', 2.7, 'Axes d''amélioration identifiés.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (156, DATE '2021-05-19', 4.0, 'Axes d''amélioration identifiés.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (55, DATE '2023-08-28', 2.7, 'Compétences techniques en progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (28, DATE '2026-04-02', 4.2, 'Des efforts sont attendus sur la communication.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (124, DATE '2026-06-17', 4.4, 'Axes d''amélioration identifiés.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (74, DATE '2021-08-23', 4.6, 'Excellente implication dans les projets.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (95, DATE '2023-07-05', 4.0, 'Axes d''amélioration identifiés.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (199, DATE '2021-08-13', 4.5, 'Excellente implication dans les projets.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (11, DATE '2024-11-23', 3.0, 'Excellente implication dans les projets.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (43, DATE '2025-07-18', 4.6, 'Excellente implication dans les projets.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (58, DATE '2021-01-08', 3.2, 'Compétences techniques en progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (133, DATE '2024-08-22', 3.3, 'Compétences techniques en progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (112, DATE '2024-10-24', 2.4, 'Performance conforme aux attentes.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (143, DATE '2021-07-22', 2.1, 'Excellente implication dans les projets.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (64, DATE '2026-08-21', 2.4, 'Performance conforme aux attentes.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (141, DATE '2021-12-05', 2.9, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (135, DATE '2026-09-18', 3.0, 'Très bonne progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (110, DATE '2022-02-15', 3.0, 'Axes d''amélioration identifiés.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (167, DATE '2025-04-22', 3.2, 'Compétences techniques en progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (199, DATE '2025-09-05', 3.7, 'Objectifs atteints.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (67, DATE '2022-01-11', 2.7, 'Objectifs atteints.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (49, DATE '2025-11-16', 4.2, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (104, DATE '2022-06-14', 5.0, 'Axes d''amélioration identifiés.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (102, DATE '2023-05-08', 4.0, 'Très bonne progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (1, DATE '2025-05-09', 4.6, 'Performance conforme aux attentes.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (200, DATE '2021-02-16', 3.2, 'Axes d''amélioration identifiés.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (6, DATE '2023-04-06', 3.8, 'Très bonne progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (23, DATE '2025-04-13', 4.4, 'Objectifs atteints.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (199, DATE '2021-10-03', 3.7, 'Performance conforme aux attentes.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (29, DATE '2021-11-09', 3.9, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (29, DATE '2021-06-06', 3.8, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (89, DATE '2023-08-03', 3.2, 'Excellente implication dans les projets.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (74, DATE '2023-09-23', 3.8, 'Compétences techniques en progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (182, DATE '2026-08-10', 2.1, 'Très bonne progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (175, DATE '2024-08-27', 3.9, 'Performance conforme aux attentes.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (103, DATE '2026-04-08', 3.8, 'Objectifs atteints.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (182, DATE '2026-03-05', 2.2, 'Des efforts sont attendus sur la communication.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (18, DATE '2022-03-07', 2.2, 'Objectifs atteints.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (100, DATE '2023-11-25', 4.1, 'Très bonne progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (79, DATE '2021-06-01', 2.3, 'Objectifs atteints.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (76, DATE '2022-01-22', 4.1, 'Performance conforme aux attentes.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (98, DATE '2025-11-19', 3.8, 'Compétences techniques en progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (136, DATE '2024-11-07', 4.1, 'Objectifs atteints.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (114, DATE '2023-03-24', 4.1, 'Très bonne progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (29, DATE '2025-10-08', 3.6, 'Compétences techniques en progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (27, DATE '2024-11-13', 3.6, 'Très bonne progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (133, DATE '2022-01-17', 3.3, 'Performance conforme aux attentes.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (125, DATE '2022-01-16', 3.7, 'Axes d''amélioration identifiés.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (18, DATE '2026-02-08', 4.1, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (141, DATE '2025-02-25', 3.0, 'Excellente implication dans les projets.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (94, DATE '2021-04-11', 3.3, 'Très bonne progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (35, DATE '2023-11-22', 3.7, 'Objectifs atteints.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (189, DATE '2021-01-04', 3.5, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (156, DATE '2022-03-17', 4.4, 'Très bonne progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (21, DATE '2023-04-02', 4.7, 'Objectifs atteints.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (82, DATE '2022-11-27', 4.2, 'Excellente implication dans les projets.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (133, DATE '2024-11-08', 2.3, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (141, DATE '2021-09-27', 2.5, 'Excellente implication dans les projets.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (120, DATE '2021-11-06', 2.5, 'Objectifs atteints.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (184, DATE '2024-05-19', 2.4, 'Des efforts sont attendus sur la communication.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (93, DATE '2024-07-01', 4.8, 'Performance conforme aux attentes.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (1, DATE '2021-04-13', 2.8, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (41, DATE '2024-07-05', 3.7, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (19, DATE '2023-01-15', 4.6, 'Compétences techniques en progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (13, DATE '2023-10-01', 2.5, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (132, DATE '2026-01-10', 4.8, 'Des efforts sont attendus sur la communication.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (53, DATE '2025-07-22', 3.2, 'Performance conforme aux attentes.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (145, DATE '2025-10-04', 2.8, 'Excellente implication dans les projets.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (131, DATE '2022-11-04', 3.6, 'Performance conforme aux attentes.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (131, DATE '2021-04-03', 2.7, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (5, DATE '2026-09-02', 3.6, 'Performance conforme aux attentes.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (40, DATE '2023-02-26', 2.3, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (150, DATE '2026-08-09', 4.2, 'Compétences techniques en progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (200, DATE '2023-01-14', 3.2, 'Performance conforme aux attentes.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (192, DATE '2021-10-05', 2.9, 'Des efforts sont attendus sur la communication.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (115, DATE '2023-06-12', 2.3, 'Très bonne progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (18, DATE '2025-05-07', 4.4, 'Excellente implication dans les projets.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (6, DATE '2023-01-04', 2.1, 'Excellente implication dans les projets.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (50, DATE '2026-11-08', 4.1, 'Excellente implication dans les projets.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (95, DATE '2022-08-25', 2.3, 'Très bonne progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (80, DATE '2022-08-21', 4.3, 'Excellente implication dans les projets.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (106, DATE '2026-02-13', 3.2, 'Performance conforme aux attentes.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (76, DATE '2026-08-06', 4.7, 'Objectifs atteints.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (87, DATE '2025-11-17', 2.3, 'Très bonne progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (196, DATE '2026-06-20', 2.2, 'Très bonne progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (99, DATE '2026-11-17', 2.4, 'Compétences techniques en progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (58, DATE '2023-03-06', 2.1, 'Compétences techniques en progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (42, DATE '2026-04-23', 4.6, 'Très bonne progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (93, DATE '2023-01-10', 3.2, 'Excellente implication dans les projets.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (91, DATE '2024-06-11', 3.4, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (4, DATE '2025-06-24', 5.0, 'Axes d''amélioration identifiés.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (195, DATE '2026-08-25', 5.0, 'Objectifs atteints.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (90, DATE '2023-10-28', 4.1, 'Axes d''amélioration identifiés.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (160, DATE '2024-03-03', 4.1, 'Excellente implication dans les projets.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (123, DATE '2025-08-01', 3.7, 'Performance conforme aux attentes.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (108, DATE '2024-12-26', 4.6, 'Axes d''amélioration identifiés.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (92, DATE '2024-04-09', 2.5, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (130, DATE '2024-09-21', 2.5, 'Excellente implication dans les projets.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (134, DATE '2025-09-19', 4.6, 'Performance conforme aux attentes.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (113, DATE '2022-04-06', 2.5, 'Des efforts sont attendus sur la communication.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (195, DATE '2025-12-09', 3.1, 'Axes d''amélioration identifiés.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (103, DATE '2022-04-11', 4.2, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (192, DATE '2026-11-28', 2.4, 'Excellente implication dans les projets.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (161, DATE '2022-01-22', 4.2, 'Objectifs atteints.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (36, DATE '2025-02-16', 4.8, 'Objectifs atteints.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (91, DATE '2026-02-16', 3.5, 'Très bonne progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (99, DATE '2021-12-24', 4.4, 'Très bonne progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (62, DATE '2025-08-14', 2.3, 'Compétences techniques en progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (98, DATE '2021-11-16', 2.8, 'Objectifs atteints.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (136, DATE '2024-05-02', 4.7, 'Compétences techniques en progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (42, DATE '2022-04-01', 3.2, 'Compétences techniques en progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (125, DATE '2025-06-11', 3.1, 'Performance conforme aux attentes.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (160, DATE '2026-03-16', 3.8, 'Objectifs atteints.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (186, DATE '2024-08-20', 3.3, 'Axes d''amélioration identifiés.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (73, DATE '2022-01-14', 3.8, 'Excellente implication dans les projets.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (41, DATE '2022-02-22', 3.3, 'Très bonne progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (184, DATE '2021-01-01', 2.6, 'Très bonne progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (65, DATE '2021-10-09', 3.9, 'Performance conforme aux attentes.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (54, DATE '2025-12-21', 3.8, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (68, DATE '2024-06-19', 3.5, 'Objectifs atteints.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (192, DATE '2024-08-25', 3.9, 'Objectifs atteints.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (168, DATE '2026-12-07', 3.8, 'Axes d''amélioration identifiés.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (24, DATE '2024-12-27', 4.1, 'Compétences techniques en progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (188, DATE '2023-02-22', 3.7, 'Très bonne progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (4, DATE '2025-03-25', 3.5, 'Excellente implication dans les projets.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (55, DATE '2024-09-06', 4.8, 'Des efforts sont attendus sur la communication.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (128, DATE '2026-07-10', 3.5, 'Performance conforme aux attentes.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (152, DATE '2022-09-26', 4.6, 'Performance conforme aux attentes.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (44, DATE '2025-01-21', 3.9, 'Des efforts sont attendus sur la communication.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (164, DATE '2024-11-27', 2.0, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (102, DATE '2022-01-08', 2.0, 'Axes d''amélioration identifiés.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (76, DATE '2021-07-28', 2.6, 'Compétences techniques en progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (195, DATE '2023-10-14', 2.4, 'Excellente implication dans les projets.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (150, DATE '2026-09-17', 4.7, 'Axes d''amélioration identifiés.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (7, DATE '2023-08-12', 5.0, 'Très bonne progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (40, DATE '2023-11-25', 4.0, 'Excellente implication dans les projets.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (55, DATE '2022-03-07', 5.0, 'Très bonne progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (82, DATE '2022-10-08', 2.8, 'Objectifs atteints.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (76, DATE '2026-04-19', 3.5, 'Axes d''amélioration identifiés.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (111, DATE '2023-07-15', 3.2, 'Très bonne progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (149, DATE '2021-11-21', 4.4, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (99, DATE '2026-02-26', 2.2, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (168, DATE '2024-01-28', 3.8, 'Très bonne progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (28, DATE '2022-06-12', 3.7, 'Des efforts sont attendus sur la communication.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (140, DATE '2026-01-18', 3.0, 'Objectifs atteints.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (86, DATE '2024-06-23', 4.8, 'Des efforts sont attendus sur la communication.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (25, DATE '2023-09-01', 4.8, 'Compétences techniques en progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (76, DATE '2023-08-02', 2.4, 'Axes d''amélioration identifiés.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (131, DATE '2024-12-14', 3.6, 'Compétences techniques en progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (103, DATE '2025-10-16', 2.6, 'Compétences techniques en progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (124, DATE '2023-11-28', 2.2, 'Performance conforme aux attentes.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (63, DATE '2026-01-03', 4.4, 'Axes d''amélioration identifiés.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (102, DATE '2021-06-26', 3.7, 'Des efforts sont attendus sur la communication.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (11, DATE '2024-12-18', 2.6, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (30, DATE '2026-10-14', 4.8, 'Axes d''amélioration identifiés.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (192, DATE '2023-03-23', 3.6, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (11, DATE '2025-07-08', 4.6, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (26, DATE '2024-05-22', 4.0, 'Objectifs atteints.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (116, DATE '2026-04-06', 2.4, 'Des efforts sont attendus sur la communication.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (119, DATE '2023-09-14', 2.8, 'Des efforts sont attendus sur la communication.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (104, DATE '2026-02-04', 2.6, 'Performance conforme aux attentes.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (111, DATE '2022-05-09', 4.0, 'Compétences techniques en progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (5, DATE '2021-07-01', 4.5, 'Compétences techniques en progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (40, DATE '2022-04-03', 2.8, 'Axes d''amélioration identifiés.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (149, DATE '2021-09-01', 4.6, 'Compétences techniques en progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (60, DATE '2024-09-11', 3.4, 'Compétences techniques en progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (9, DATE '2021-09-26', 3.1, 'Objectifs atteints.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (173, DATE '2023-02-22', 4.2, 'Objectifs atteints.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (148, DATE '2023-01-04', 3.9, 'Des efforts sont attendus sur la communication.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (151, DATE '2022-12-21', 3.6, 'Excellente implication dans les projets.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (101, DATE '2021-06-08', 2.5, 'Compétences techniques en progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (168, DATE '2023-09-16', 2.9, 'Axes d''amélioration identifiés.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (128, DATE '2024-03-24', 3.3, 'Très bonne progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (33, DATE '2024-06-16', 4.9, 'Axes d''amélioration identifiés.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (85, DATE '2024-04-07', 4.2, 'Compétences techniques en progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (41, DATE '2024-12-09', 3.3, 'Axes d''amélioration identifiés.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (162, DATE '2022-08-24', 3.6, 'Très bonne progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (145, DATE '2026-03-05', 3.1, 'Performance conforme aux attentes.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (13, DATE '2024-09-06', 2.0, 'Axes d''amélioration identifiés.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (190, DATE '2025-09-02', 3.3, 'Performance conforme aux attentes.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (42, DATE '2023-01-05', 4.3, 'Compétences techniques en progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (116, DATE '2026-01-13', 2.7, 'Axes d''amélioration identifiés.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (25, DATE '2022-06-21', 2.1, 'Axes d''amélioration identifiés.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (104, DATE '2023-12-11', 2.7, 'Performance conforme aux attentes.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (186, DATE '2024-07-22', 4.9, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (162, DATE '2024-06-12', 2.2, 'Très bonne progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (78, DATE '2023-03-12', 4.1, 'Très bonne progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (138, DATE '2022-03-23', 2.0, 'Compétences techniques en progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (48, DATE '2026-08-02', 3.5, 'Des efforts sont attendus sur la communication.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (188, DATE '2024-05-28', 2.8, 'Très bonne progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (106, DATE '2021-07-13', 3.8, 'Des efforts sont attendus sur la communication.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (82, DATE '2025-11-28', 4.7, 'Objectifs atteints.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (34, DATE '2021-03-08', 2.3, 'Objectifs atteints.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (156, DATE '2023-01-04', 2.2, 'Compétences techniques en progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (63, DATE '2026-04-15', 3.2, 'Excellente implication dans les projets.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (64, DATE '2026-06-02', 5.0, 'Excellente implication dans les projets.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (68, DATE '2023-08-07', 3.6, 'Performance conforme aux attentes.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (70, DATE '2022-12-16', 5.0, 'Très bonne progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (106, DATE '2021-12-15', 4.4, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (20, DATE '2023-08-14', 4.4, 'Objectifs atteints.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (140, DATE '2022-05-20', 3.4, 'Compétences techniques en progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (130, DATE '2025-08-05', 4.6, 'Des efforts sont attendus sur la communication.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (164, DATE '2021-02-28', 4.8, 'Très bonne progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (151, DATE '2026-01-26', 4.0, 'Excellente implication dans les projets.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (4, DATE '2021-04-05', 4.6, 'Des efforts sont attendus sur la communication.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (75, DATE '2022-09-10', 3.2, 'Des efforts sont attendus sur la communication.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (171, DATE '2025-07-13', 4.4, 'Des efforts sont attendus sur la communication.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (110, DATE '2024-04-27', 3.8, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (100, DATE '2026-11-13', 3.9, 'Objectifs atteints.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (63, DATE '2021-07-05', 3.9, 'Compétences techniques en progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (69, DATE '2023-06-15', 3.5, 'Axes d''amélioration identifiés.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (89, DATE '2025-12-09', 2.8, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (195, DATE '2023-06-19', 4.1, 'Objectifs atteints.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (51, DATE '2026-01-02', 2.5, 'Axes d''amélioration identifiés.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (147, DATE '2023-03-18', 4.7, 'Des efforts sont attendus sur la communication.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (155, DATE '2022-02-24', 2.3, 'Excellente implication dans les projets.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (154, DATE '2023-06-15', 2.2, 'Compétences techniques en progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (89, DATE '2024-09-26', 2.8, 'Très bonne progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (30, DATE '2025-04-21', 3.7, 'Compétences techniques en progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (132, DATE '2025-05-13', 2.1, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (157, DATE '2022-03-11', 4.9, 'Objectifs atteints.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (164, DATE '2022-02-15', 2.6, 'Des efforts sont attendus sur la communication.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (110, DATE '2021-05-12', 3.7, 'Performance conforme aux attentes.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (124, DATE '2025-01-22', 4.9, 'Axes d''amélioration identifiés.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (182, DATE '2022-09-26', 3.1, 'Performance conforme aux attentes.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (57, DATE '2026-04-16', 2.8, 'Très bonne progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (19, DATE '2022-08-21', 2.1, 'Des efforts sont attendus sur la communication.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (46, DATE '2022-10-05', 3.7, 'Très bonne progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (174, DATE '2025-02-24', 2.8, 'Très bonne progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (192, DATE '2025-05-22', 4.9, 'Axes d''amélioration identifiés.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (153, DATE '2023-12-27', 4.0, 'Excellente implication dans les projets.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (18, DATE '2026-02-18', 3.1, 'Très bonne progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (51, DATE '2026-11-24', 3.3, 'Compétences techniques en progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (28, DATE '2021-11-20', 3.6, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (61, DATE '2026-06-16', 3.1, 'Objectifs atteints.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (9, DATE '2021-06-28', 2.2, 'Excellente implication dans les projets.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (173, DATE '2021-06-28', 3.1, 'Performance conforme aux attentes.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (98, DATE '2025-10-07', 2.5, 'Des efforts sont attendus sur la communication.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (62, DATE '2022-12-09', 3.3, 'Compétences techniques en progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (140, DATE '2025-10-02', 4.8, 'Des efforts sont attendus sur la communication.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (67, DATE '2025-07-09', 5.0, 'Performance conforme aux attentes.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (46, DATE '2021-03-21', 3.6, 'Très bonne progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (95, DATE '2024-07-08', 5.0, 'Axes d''amélioration identifiés.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (127, DATE '2025-08-18', 4.5, 'Des efforts sont attendus sur la communication.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (36, DATE '2026-05-07', 3.1, 'Performance conforme aux attentes.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (144, DATE '2023-01-18', 4.6, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (145, DATE '2023-04-26', 3.3, 'Compétences techniques en progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (111, DATE '2024-10-13', 4.4, 'Très bonne progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (4, DATE '2026-11-14', 2.2, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (95, DATE '2025-12-25', 2.2, 'Axes d''amélioration identifiés.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (159, DATE '2026-12-23', 4.1, 'Très bonne progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (90, DATE '2024-07-20', 5.0, 'Excellente implication dans les projets.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (155, DATE '2021-07-16', 2.1, 'Compétences techniques en progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (23, DATE '2025-05-06', 2.7, 'Axes d''amélioration identifiés.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (100, DATE '2021-10-22', 3.3, 'Excellente implication dans les projets.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (159, DATE '2021-01-13', 2.0, 'Objectifs atteints.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (35, DATE '2023-06-08', 2.4, 'Objectifs atteints.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (191, DATE '2026-02-12', 4.2, 'Objectifs atteints.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (72, DATE '2026-03-25', 2.2, 'Axes d''amélioration identifiés.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (121, DATE '2026-08-04', 3.7, 'Compétences techniques en progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (12, DATE '2023-09-26', 4.3, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (169, DATE '2024-08-06', 2.3, 'Compétences techniques en progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (195, DATE '2023-09-13', 2.0, 'Objectifs atteints.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (200, DATE '2025-02-12', 4.2, 'Des efforts sont attendus sur la communication.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (119, DATE '2025-01-01', 2.1, 'Très bonne progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (127, DATE '2021-02-13', 3.3, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (20, DATE '2026-03-18', 2.6, 'Excellente implication dans les projets.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (132, DATE '2021-11-04', 3.1, 'Excellente implication dans les projets.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (44, DATE '2026-02-14', 5.0, 'Excellente implication dans les projets.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (55, DATE '2023-04-27', 3.7, 'Compétences techniques en progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (10, DATE '2024-07-18', 2.5, 'Des efforts sont attendus sur la communication.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (102, DATE '2022-01-11', 2.0, 'Objectifs atteints.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (28, DATE '2022-12-07', 4.1, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (131, DATE '2021-11-24', 4.7, 'Excellente implication dans les projets.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (88, DATE '2026-10-01', 3.5, 'Objectifs atteints.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (150, DATE '2021-02-02', 3.7, 'Performance conforme aux attentes.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (10, DATE '2025-12-18', 4.4, 'Performance conforme aux attentes.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (11, DATE '2023-10-17', 4.8, 'Performance conforme aux attentes.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (190, DATE '2023-02-12', 2.9, 'Axes d''amélioration identifiés.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (100, DATE '2023-01-05', 2.0, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (7, DATE '2023-10-17', 2.6, 'Très bonne progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (151, DATE '2022-05-18', 3.4, 'Axes d''amélioration identifiés.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (73, DATE '2021-04-18', 4.8, 'Performance conforme aux attentes.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (192, DATE '2021-04-09', 2.6, 'Très bonne progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (105, DATE '2021-07-06', 2.5, 'Excellente implication dans les projets.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (130, DATE '2024-01-16', 2.1, 'Très bonne progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (171, DATE '2023-02-19', 3.6, 'Objectifs atteints.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (29, DATE '2026-06-11', 4.4, 'Axes d''amélioration identifiés.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (86, DATE '2025-10-04', 4.9, 'Performance conforme aux attentes.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (173, DATE '2025-05-11', 2.7, 'Excellente implication dans les projets.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (9, DATE '2024-10-26', 4.4, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (29, DATE '2024-08-14', 2.2, 'Axes d''amélioration identifiés.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (169, DATE '2023-08-01', 2.2, 'Excellente implication dans les projets.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (33, DATE '2023-08-27', 4.5, 'Très bonne progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (184, DATE '2025-08-28', 2.2, 'Performance conforme aux attentes.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (60, DATE '2025-02-14', 3.1, 'Excellente implication dans les projets.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (15, DATE '2026-04-21', 3.5, 'Axes d''amélioration identifiés.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (162, DATE '2022-03-22', 3.0, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (93, DATE '2024-10-27', 3.0, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (194, DATE '2026-09-27', 4.4, 'Objectifs atteints.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (172, DATE '2021-02-25', 3.4, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (197, DATE '2023-11-04', 2.5, 'Très bonne progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (169, DATE '2026-02-14', 3.8, 'Excellente implication dans les projets.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (176, DATE '2026-10-13', 2.0, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (118, DATE '2023-02-11', 3.4, 'Excellente implication dans les projets.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (30, DATE '2021-08-01', 3.8, 'Compétences techniques en progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (70, DATE '2024-05-14', 3.0, 'Objectifs atteints.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (9, DATE '2023-10-12', 3.8, 'Très bonne progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (118, DATE '2024-08-28', 2.2, 'Performance conforme aux attentes.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (127, DATE '2023-09-17', 3.3, 'Compétences techniques en progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (122, DATE '2023-04-25', 4.6, 'Performance conforme aux attentes.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (83, DATE '2026-06-18', 2.4, 'Des efforts sont attendus sur la communication.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (11, DATE '2025-09-10', 3.8, 'Très bonne progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (58, DATE '2025-03-03', 4.1, 'Très bonne progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (129, DATE '2023-08-03', 2.3, 'Performance conforme aux attentes.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (124, DATE '2021-10-11', 3.2, 'Compétences techniques en progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (184, DATE '2026-11-11', 3.1, 'Performance conforme aux attentes.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (111, DATE '2023-05-07', 4.4, 'Des efforts sont attendus sur la communication.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (149, DATE '2022-08-05', 2.1, 'Excellente implication dans les projets.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (27, DATE '2024-02-12', 3.6, 'Objectifs atteints.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (177, DATE '2023-04-24', 2.2, 'Des efforts sont attendus sur la communication.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (25, DATE '2026-12-01', 2.7, 'Excellente implication dans les projets.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (132, DATE '2025-09-25', 3.7, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (168, DATE '2022-09-02', 4.6, 'Objectifs atteints.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (177, DATE '2022-02-11', 4.2, 'Des efforts sont attendus sur la communication.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (111, DATE '2025-05-15', 4.1, 'Objectifs atteints.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (17, DATE '2022-09-04', 4.2, 'Compétences techniques en progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (19, DATE '2022-11-18', 2.6, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (44, DATE '2022-11-20', 4.1, 'Performance conforme aux attentes.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (97, DATE '2024-05-22', 4.7, 'Très bonne progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (153, DATE '2022-03-18', 2.9, 'Très bonne progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (102, DATE '2022-11-09', 2.6, 'Axes d''amélioration identifiés.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (149, DATE '2022-11-18', 2.2, 'Compétences techniques en progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (195, DATE '2021-08-22', 4.7, 'Objectifs atteints.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (181, DATE '2025-05-01', 4.7, 'Compétences techniques en progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (189, DATE '2024-03-03', 4.8, 'Performance conforme aux attentes.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (98, DATE '2025-02-19', 4.9, 'Des efforts sont attendus sur la communication.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (169, DATE '2026-06-22', 2.9, 'Performance conforme aux attentes.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (195, DATE '2024-11-13', 3.6, 'Très bonne progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (10, DATE '2023-07-23', 4.7, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (50, DATE '2026-11-01', 2.7, 'Excellente implication dans les projets.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (92, DATE '2024-11-03', 2.1, 'Des efforts sont attendus sur la communication.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (157, DATE '2024-06-27', 3.4, 'Objectifs atteints.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (105, DATE '2021-04-24', 2.2, 'Très bonne progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (15, DATE '2023-02-14', 3.2, 'Axes d''amélioration identifiés.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (6, DATE '2026-11-20', 4.6, 'Objectifs atteints.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (77, DATE '2025-01-10', 4.7, 'Des efforts sont attendus sur la communication.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (166, DATE '2025-03-19', 3.7, 'Objectifs atteints.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (21, DATE '2022-11-17', 4.8, 'Excellente implication dans les projets.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (184, DATE '2021-11-19', 4.8, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (102, DATE '2022-12-24', 2.5, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (142, DATE '2026-09-04', 3.1, 'Compétences techniques en progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (114, DATE '2023-12-05', 3.2, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (111, DATE '2021-08-01', 4.4, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (28, DATE '2025-02-06', 5.0, 'Performance conforme aux attentes.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (25, DATE '2025-05-22', 4.8, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (118, DATE '2022-02-13', 3.0, 'Excellente implication dans les projets.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (185, DATE '2021-10-16', 4.1, 'Axes d''amélioration identifiés.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (67, DATE '2023-08-26', 2.1, 'Axes d''amélioration identifiés.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (151, DATE '2022-10-17', 2.9, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (67, DATE '2024-10-22', 2.9, 'Excellente implication dans les projets.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (46, DATE '2021-03-15', 4.4, 'Performance conforme aux attentes.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (91, DATE '2023-01-14', 2.4, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (122, DATE '2023-10-08', 3.8, 'Très bonne progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (72, DATE '2024-08-28', 3.8, 'Compétences techniques en progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (126, DATE '2022-12-23', 3.0, 'Objectifs atteints.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (183, DATE '2025-07-12', 4.5, 'Performance conforme aux attentes.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (32, DATE '2024-11-22', 2.3, 'Des efforts sont attendus sur la communication.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (113, DATE '2022-02-10', 4.0, 'Très bonne progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (121, DATE '2026-05-16', 5.0, 'Excellente implication dans les projets.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (38, DATE '2025-08-12', 3.1, 'Axes d''amélioration identifiés.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (140, DATE '2023-04-26', 4.2, 'Des efforts sont attendus sur la communication.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (57, DATE '2026-09-11', 2.8, 'Performance conforme aux attentes.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (102, DATE '2024-11-08', 2.4, 'Excellente implication dans les projets.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (137, DATE '2024-04-07', 4.4, 'Des efforts sont attendus sur la communication.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (66, DATE '2025-07-14', 2.6, 'Performance conforme aux attentes.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (107, DATE '2023-08-08', 2.3, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (48, DATE '2025-06-28', 3.0, 'Objectifs atteints.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (33, DATE '2023-12-10', 2.3, 'Performance conforme aux attentes.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (125, DATE '2022-04-02', 2.0, 'Excellente implication dans les projets.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (156, DATE '2026-02-22', 4.2, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (155, DATE '2025-12-07', 3.3, 'Compétences techniques en progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (22, DATE '2024-11-23', 4.2, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (11, DATE '2026-06-10', 3.5, 'Axes d''amélioration identifiés.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (96, DATE '2022-01-11', 2.2, 'Excellente implication dans les projets.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (110, DATE '2022-07-07', 3.8, 'Objectifs atteints.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (130, DATE '2022-11-01', 3.7, 'Très bonne progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (149, DATE '2021-07-06', 3.9, 'Des efforts sont attendus sur la communication.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (141, DATE '2022-06-07', 2.3, 'Performance conforme aux attentes.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (35, DATE '2022-04-10', 4.1, 'Très bonne progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (160, DATE '2025-11-14', 3.9, 'Performance conforme aux attentes.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (175, DATE '2026-01-10', 3.6, 'Objectifs atteints.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (5, DATE '2023-03-07', 3.8, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (1, DATE '2021-02-21', 3.9, 'Axes d''amélioration identifiés.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (158, DATE '2026-08-04', 4.7, 'Performance conforme aux attentes.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (134, DATE '2023-10-11', 2.8, 'Des efforts sont attendus sur la communication.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (154, DATE '2025-02-13', 2.0, 'Compétences techniques en progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (174, DATE '2021-06-02', 2.3, 'Excellente implication dans les projets.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (181, DATE '2021-11-24', 4.4, 'Objectifs atteints.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (7, DATE '2026-05-15', 4.2, 'Compétences techniques en progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (163, DATE '2021-12-01', 4.6, 'Performance conforme aux attentes.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (10, DATE '2022-05-19', 4.2, 'Axes d''amélioration identifiés.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (53, DATE '2021-06-23', 2.1, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (173, DATE '2022-01-22', 4.3, 'Axes d''amélioration identifiés.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (31, DATE '2025-04-24', 2.4, 'Objectifs atteints.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (31, DATE '2022-01-22', 4.9, 'Très bonne progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (165, DATE '2024-07-17', 3.2, 'Compétences techniques en progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (16, DATE '2026-10-28', 2.6, 'Performance conforme aux attentes.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (171, DATE '2024-10-21', 3.4, 'Excellente implication dans les projets.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (165, DATE '2023-04-03', 3.5, 'Axes d''amélioration identifiés.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (199, DATE '2024-07-23', 3.3, 'Compétences techniques en progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (65, DATE '2024-05-04', 4.2, 'Axes d''amélioration identifiés.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (32, DATE '2026-03-09', 3.3, 'Objectifs atteints.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (34, DATE '2021-02-15', 3.3, 'Excellente implication dans les projets.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (156, DATE '2024-05-14', 2.7, 'Très bonne progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (46, DATE '2022-07-02', 3.3, 'Objectifs atteints.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (43, DATE '2025-12-03', 4.6, 'Des efforts sont attendus sur la communication.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (135, DATE '2022-11-03', 2.5, 'Performance conforme aux attentes.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (20, DATE '2023-04-24', 2.7, 'Bonne autonomie.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (54, DATE '2022-11-19', 3.6, 'Très bonne progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (60, DATE '2022-03-25', 3.9, 'Très bonne progression.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (131, DATE '2026-09-01', 2.6, 'Des efforts sont attendus sur la communication.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (143, DATE '2023-01-19', 2.9, 'Performance conforme aux attentes.');
INSERT INTO review (employee_id, review_date, score, comments) VALUES (159, DATE '2026-04-26', 4.2, 'Très bonne progression.');
COMMIT;